name: Run tests for PR

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  composer-checkup:
    name: "Run PHP tests for PR"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source branch for CI"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: redis

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache Composer Downloads"
        uses: actions/cache@v2
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: "Cache PHP dependencies"
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: "Install PHP dependencies"
        run: |
          composer install --no-interaction --prefer-dist

      - name: "PHPCS / PHPComp / PHPStan / PHPUnit checkup"
        run: composer checkup
